"""empty message

Revision ID: 20214b722b68
Revises: 97dee9d0c307
Create Date: 2021-05-01 09:47:54.498589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20214b722b68'
down_revision = '97dee9d0c307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_roles', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_roles', type_='unique')
    # ### end Alembic commands ###
