"""empty message

Revision ID: 83008b5d8794
Revises: 2fc28a2588e6
Create Date: 2021-05-01 23:32:22.772921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83008b5d8794'
down_revision = '2fc28a2588e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_roles', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_roles', type_='unique')
    # ### end Alembic commands ###
